In [1]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv(r"C:\worldcitiespop.csv")

C:\Users\itole\AppData\Local\Temp\ipykernel_77960\3803636654.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(r"C:\Users\itole\Downloads\worldcitiespop.csv")

In [7]:
df.dropna(how="any")

,Country,City,AccentCity,Region,Population,Latitude,Longitude
6,ad,andorra la vella,Andorra la Vella,7.0,20430.0,42.500000,1.516667
20,ad,canillo,Canillo,2.0,3292.0,42.566667,1.600000
32,ad,encamp,Encamp,3.0,11224.0,42.533333,1.583333
49,ad,la massana,La Massana,4.0,7211.0,42.550000,1.516667
53,ad,les escaldes,Les Escaldes,8.0,15854.0,42.500000,1.533333
...,...,...,...,...,...,...,...
3173646,zw,redcliffe,Redcliffe,6,38231.0,-19.033333,29.783333
3173676,zw,rusape,Rusape,4,23761.0,-18.533333,32.116667
3173737,zw,shurugwi,Shurugwi,7,17107.0,-19.666667,30.000000
3173892,zw,victoria falls,Victoria Falls,0,36702.0,-17.933333,25.833333
3173957,zw,zvishavane,Zvishavane,7,79876.0,-20.333333,30.033333

In [11]:
filtered_df = df[df['Population'] > 1000]

In [12]:
filtered_df

,Country,City,AccentCity,Region,Population,Latitude,Longitude
6,ad,andorra la vella,Andorra la Vella,7.0,20430.0,42.500000,1.516667
20,ad,canillo,Canillo,2.0,3292.0,42.566667,1.600000
32,ad,encamp,Encamp,3.0,11224.0,42.533333,1.583333
49,ad,la massana,La Massana,4.0,7211.0,42.550000,1.516667
53,ad,les escaldes,Les Escaldes,8.0,15854.0,42.500000,1.533333
...,...,...,...,...,...,...,...
3173646,zw,redcliffe,Redcliffe,6,38231.0,-19.033333,29.783333
3173676,zw,rusape,Rusape,4,23761.0,-18.533333,32.116667
3173737,zw,shurugwi,Shurugwi,7,17107.0,-19.666667,30.000000
3173892,zw,victoria falls,Victoria Falls,0,36702.0,-17.933333,25.833333
3173957,zw,zvishavane,Zvishavane,7,79876.0,-20.333333,30.033333

In [ ]:
filtered_df.to_csv(r"C:\worldcitiespop2.csv", index=False)